version: '3.8'

services:
  # Node js web application
  # Launched with npm
  web:
    build: ./web
    container_name: web-server
    command: npm run dev
    volumes:
      - ./web:/web
    ports:
      - "3000:3000"
    env_file:
      - ./web/.env
    depends_on:
      - mongodb
      # - keycloak

      # MongoDB as database for web application and
      # scraped data
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./nft_volume:/data/db
    ports:
      - "27017:27017"

  # FastAPI w/ Python as REST API
  api:
    build: ./api
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  # Selenium w/ Python to scrape data
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - 4444:4444

  nft_scraper:
    build: ./scrapers
    container_name: nft_scraper
    ports:
      - "8888:8888"
    #command: ["pipenv", "run", "jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
    command: [ "pipenv", "run", "python", "nft.py" ]
    restart: on-failure
    depends_on:
      - selenium
      - api
    volumes:
      - ./scrapers:/home/dev/code/

  crypto_scraper:
    build: ./scrapers
    container_name: crypto_scraper
    ports:
      - "8887:8887"
    command: [ "pipenv", "run", "python", "crypto.py" ]
    depends_on:
      - selenium
      - api
    restart: on-failure
    volumes:
      - ./scrapers:/home/dev/code/
  # PostgreSQL as database for Keycload
  # postgres:
  #   image: postgres:12
  #   container_name: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: keycloak
  #     POSTGRES_USER: keycloak
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - ./auth_volume:/var/lib/postgresql/data

  # Keycloak ft. PostgreSQL for authentification
  # keycloak:
  #   image: quay.io/keycloak/keycloak:15.0.0
  #   depends_on:
  #     - postgres
  #   container_name: auth
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - KEYCLOAK_USER=admin
  #     - KEYCLOAK_PASSWORD=admin
  #     - DB_VENDOR=postgres
  #     - DB_USER=keycloak
  #     - DB_PASSWORD=password
  #     - DB_ADDR=postgres
  #     - DB_DATABASE=keycloak
  #     - KEYCLOAK_IMPORT=/opt/jboss/keycloak/nftmarketplace-realm.json
  #   volumes:
  #   - ./keycloak/nftmarketplace-realm.json:/opt/jboss/keycloak/nftmarketplace-realm.json

networks:
  default:
    driver: bridge

volumes:
  nft_volume: null
  auth_volume: null
